[package]
name = "succinct-client"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.4.2", features = ["serde"] }
anyhow = "1.0.75"
ethers = "2.0.11"
log = "0.4.20"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
toml = "0.8.8"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
